function selection = radioDialog(options, title)

    selection = 0;

    radioDlg = figure("Name", title, "MenuBar", "none", 'ToolBar', 'none', ...
        'Color', [.66 .76 1], 'WindowStyle', 'modal', 'NumberTitle', 'off');
    radioDlg.Position(3:4) = [460 345];

    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'String', 'Which kind of comparison would you like to make?', ...
        'Position', [.05 .85 .9 .1], 'FontSize', 12, 'BackgroundColor', [.66 .76 1]);
    
    btngroup = uibuttongroup(radioDlg, 'Units', 'normalized', 'Position', [0.05 0.2 0.9 0.6], ...
        'BorderType', 'none', 'BackgroundColor', [.66 .76 1]);
    btgroup.UserData.selection = selection;
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
    'Position', [.05 .85 .9 .15], 'String', options{1}, ...
    'FontSize', 12, 'Tag', '1', 'BackgroundColor', [.66 .76 1]);
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
    'Position', [.05 .68 .9 .15], 'String', options{2}, ...
    'FontSize', 12, 'Tag', '2', 'BackgroundColor', [.66 .76 1]);
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
    'Position', [.05 .51 .9 .15], 'String', options{3}, ...
    'FontSize', 12, 'Tag', '3', 'BackgroundColor', [.66 .76 1]);
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
    'Position', [.05 .34 .9 .15], 'String', options{4}, ...
    'FontSize', 12, 'Tag', '4', 'BackgroundColor', [.66 .76 1]);
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
    'Position', [.05 .17 .9 .15], 'String', options{5}, ...
    'FontSize', 12, 'Tag', '5', 'BackgroundColor', [.66 .76 1]);   
    uicontrol(btngroup, 'Style', 'radiobutton', 'Units', 'normalized', ...
        'Position', [.05 0 .9 .15], 'String', options{6}, ...
        'FontSize', 12, 'Tag', '6', 'BackgroundColor', [.66 .76 1]);

    uicontrol('Style', 'pushbutton', 'String', 'Cancel', ...
        'Units', 'normalized', 'Position', [.62 .02 .15 .1], 'FontSize', 12, ...
        'Callback', {@btnPressed, btngroup});
    uicontrol('Style', 'pushbutton', 'String', 'OK', ...
        'Units', 'normalized', 'Position', [.8 .02 .15 .1], 'FontSize', 12, ...
        'Callback', {@btnPressed, btngroup});

    uiwait(radioDlg);

    selection = btngroup.UserData.selection;

    delete(radioDlg);

    function btnPressed(src, event, btngroup)
        if strcmp(src.String, 'Cancel')
            btngroup.UserData.selection = 0;
        else
            btngroup.UserData.selection = str2double(btngroup.SelectedObject.Tag);
        end
        uiresume(radioDlg);
    end
    
end